/**
 * Central user-facing copy. Non-technical "simple mode" wording lives here so
 * we never scatter jargon across components. Code identifiers keep their
 * original technical names; only the DISPLAYED text comes from this file.
 */
export const COPY = {
  // Product story (local-first + optional Cloud)
  productTagline: "Your private AI workspace — local or Cloud",
  welcomeHint:
    "Use Private for on-device models, or switch to Cloud in the top bar when you want NELA Cloud.",

  // Tools menu (was: RAG / Web search / Thinking)
  toolSearchDocs: "Search my documents",
  toolSearchDocsHint: "Look through documents you've added to answer your question.",
  toolSearchWeb: "Search the web",
  toolSearchWebHint:
    "Lets the model look things up online when it needs live facts. NELA does not search the web on every message.",
  toolSearchFiles: "Search my files",
  toolSearchFilesHint:
    "Search folders indexed by NELA’s File Indexer (smart keyword + meaning search on your machine).",
  toolShowReasoning: "Show reasoning", // advanced-only; see Task 12
  toolShowReasoningHint:
    "Show the assistant's step-by-step thinking (Cloud Smart and Deep only).",
  toolShowReasoningFastHint:
    "Step-by-step reasoning is available in Cloud Smart and Deep, not Fast.",

  // Attach menu (was: Add Files / Ingest / direct)
  addDocumentsTitle: "Attach files",
  addDocumentsHint: "PDF, Word, PowerPoint, images, text, and more.",
  attachToChatTitle: "Attach to this chat",
  attachToChatHint: "PDF, Office, images, text, spreadsheets, and more. Not indexed. You can also drag files onto the chat.",
  dropFilesTitle: "Drop to attach",
  dropFilesHint: "PDF, Office, images, text, and more — attached to this chat only.",
  addToLibraryTitle: "Add to library",
  addToLibraryHint: "Index into your document library for Search my documents.",
  addFolderTitle: "Add a folder",
  addFolderHint: "Add every supported file in a folder.",
  uploadImageTitle: "Upload an image",
  uploadImageHint: "JPG, PNG, WEBP, GIF, or BMP.",
  attachCloudDisclosure:
    "Files will be sent to NELA Cloud/OpenRouter for this conversation.",
  attachLocalDestination: "Local",
  attachCloudDestination: "Cloud",
  attachScannedPdf: "Scanned PDF (OCR)",

  // Connectors (chat "+" menu)
  connectorsMenuTitle: "Connectors",
  connectorsMenuHint: "Google Drive and other cloud apps — sync into Search my files.",
  connectProviderHint: "Connect and sync into Search my files.",

  // Knowledge base (was: Knowledge Base / chunks / phaseN / ingesting)
  libraryTitle: "Document Library",
  libraryEmpty: "No documents yet. Use \u201CAdd documents\u201D to get started.",
  libraryDeleteAll: "Delete all",
  libraryDeleteAllConfirm:
    "Remove every document from the library? This cannot be undone.",
  docStateAdding: "Adding\u2026",
  docStateReady: "Ready",
  docStateEnhanced: "Enhanced",
  processing: "Processing\u2026",

  // Sources (was: score: 0.0473)
  sourcesTitle: "Sources",
  relevanceHigh: "High relevance",
  relevanceMedium: "Medium relevance",
  relevanceLow: "Low relevance",

  // Auto-scan (was: Auto-scan Folders / watched paths)
  syncFolderTitle: "Keep a folder in sync",
  syncFolderReassure: "Files are read and indexed on this device only.",
  syncFolderEmpty: "No folders yet. Add one to keep it in sync automatically.",

  // Privacy indicator — scoped to current mode; do not claim “never uploads”
  privacyPrivate: "Private \u00B7 on this device",
  privacyPrivateTooltip:
    "Private mode: chat and document inference run on this device. Internet may still be used if you download a model, turn on web search, or switch to Cloud.",
  privacyPublic: "Public \u00B7 uses the web",
  privacyPublicTooltip:
    "Web search is enabled. NELA may fetch pages from the internet to help answer your question.",
  privacyNetwork: "Downloading model\u2026",
  privacyNetworkTooltip:
    "NELA is downloading a model from the internet right now. Your document library stays on this device unless you attach files in Cloud mode.",

  // Mode banner (Private local vs Cloud)
  modePrivateLabel: "Private",
  modePrivateSub: "Runs on this device",
  modePrivateTooltip:
    "Private mode: text answers run on this device. Switch to Cloud to create presentations, spreadsheets, HTML, or other file artifacts.",
  modeCloudLabel: "Cloud",
  modeCloudSub: "Uses the internet",
  modeCloudTooltip:
    "Cloud mode: answers are generated by NELA Cloud over the internet (Fast / Smart / Deep). Prompts and chat attachments you send in Cloud leave this device. File artifacts (PPT, Excel, HTML) are created here.",
  modeToggleAria: "Switch between Private (on device) and Cloud (internet)",
  privateModeArtifactsCloudOnly:
    "Private mode is text-only. Switch to Cloud in the top bar to create presentations, spreadsheets, HTML dashboards, or other file artifacts.",
  modeWebOn: "Web on",
  modeDownloading: "Downloading model\u2026",

  // Response style (Task 4)
  responseStyleLabel: "Response style",
  responseStylePrecise: "Precise",
  responseStylePreciseHint:
    "Focused, consistent answers. Best for facts and analysis. (Lower temperature.)",
  responseStyleBalanced: "Balanced",
  responseStyleBalancedHint:
    "A mix of accuracy and flexibility. Good default. (Medium temperature.)",
  responseStyleCreative: "Creative",
  responseStyleCreativeHint:
    "More varied, imaginative answers. (Higher temperature and sampling.)",

  // Intelligence tiers (model mode)
  intelligenceFast: "Fast",
  intelligenceFastHint: "Quick answers — tools on, no step-by-step reasoning.",
  intelligenceSmart: "Smart",
  intelligenceSmartHint: "Balanced reasoning for everyday questions.",
  intelligenceDeep: "Deep",
  intelligenceDeepHint: "Best quality — may take longer to load.",
  intelligenceAuto: "Auto",
  intelligenceAutoHint:
    "On cloud, pick Fast / Smart / Deep automatically. On this device, uses Smart.",
  intelligenceCustom: "Custom",
  intelligenceCustomHint: "A specific model you chose manually.",
  intelligenceChooseModel: "Choose specific model\u2026",
  intelligenceBackToTiers: "Back to Fast / Smart / Deep / Auto",
  intelligenceDeepLoadWarning:
    "Deep mode uses a large model and may take 1\u20132 minutes to load the first time. Continue?",
  intelligenceDownloadPrompt: (name: string, sizeLabel: string) =>
    `${name} is not installed yet${sizeLabel ? ` (${sizeLabel})` : ""}. Download it now?`,

  // Generic errors — always include a next step
  errorNotReady:
    "NELA is still getting ready. Wait a moment, then try again.",
  errorGeneric: "Something went wrong. Please try again.",
  errorCancelled: "Stopped. Send another message whenever you're ready.",
  errorTimeout: "That took too long. Please try again.",
  errorMemory:
    "Your computer ran low on memory. Try a smaller model or close other apps, then retry.",
  errorCloudUnreachable:
    "We couldn't reach NELA Cloud. Check your internet connection and try again.",
  errorCloudBusy:
    "NELA Cloud is busy right now. Wait a moment, then try again.",
  errorRateLimited:
    "Too many requests just now. Wait a few seconds, then try again.",
  errorAuthCredentials:
    "That email or password doesn't look right. Check them and try again.",
  errorEmailExists:
    "An account with that email already exists. Sign in instead, or use a different email.",
  errorSessionExpired:
    "Your NELA Cloud session expired. Please sign in again.",
  errorPlan:
    "Your plan doesn't cover this yet. Open Cloud settings or upgrade on the website.",
  errorUpgradeRequired:
    "Smart and Deep need credits. Your free trial may have ended — buy a pack or upgrade from Cloud settings.",
  errorCreditsEmpty:
    "You're out of credits. Buy a pack or wait for your next monthly grant.",
  errorFastQuota:
    "You've used the free Fast allowance (8 / 6h). Wait for the window to reset, or buy credits for unlimited Fast and Smart/Deep.",
  errorOpenBrowser:
    "We couldn't open your browser. Open nela.ai manually, then try again.",
  errorNotSignedIn:
    "You're not signed in yet. Sign in from Profile to continue.",
  errorSignInTimeout: "Sign-in took too long. Please try again.",
  errorDeviceLink:
    "That device code didn't work. Generate a new code on desktop and try again.",
  errorBilling:
    "We couldn't complete billing. Check your payment details on the website and try again.",
  errorArtifact:
    "We couldn't finish that file. Try again, or ask for a simpler version.",
  /** Generation stopped mid-file (token limit / incomplete HTML). */
  errorArtifactTruncated:
    "That file was cut off before it finished. Ask me to continue, or try a shorter version (fewer slides or sections).",
  /** Almost no usable content in the generated file. */
  errorArtifactEmpty:
    "I couldn't build usable content for that file. Try again with a clearer brief — for example, a 5-slide pitch with one chart, or a simple budget sheet.",
  /** Preview exists in the panel but disk save / validation failed. */
  errorArtifactSave:
    "A preview is ready in the panel, but we couldn't save the file. You can still review it there, or try again.",
  /** Spreadsheet / CSV specific failure. */
  errorArtifactSpreadsheet:
    "We couldn't finish that spreadsheet. Try a simpler table layout, or ask again with fewer sheets.",
  errorWebSearch:
    "Web search didn't work just now. Try again, or continue without live sources.",
  errorFileLoad:
    "We couldn't open that file. Check the path and try again.",
  retry: "Try again",
  retryPrompt: "Retry this prompt",

  // Slash commands
  slashCommandsHint: "Type / for commands (ppt, excel, html, web, rag, files)",
} as const;

export type CopyKey = keyof typeof COPY;
